export const UpdateCurrentUser = 'UPDATE_CURRENT_USER'
export const UpdateListing = 'UPDATE_LISTING'
export const CreateListing = 'CREATE_LISTING'
export const UpdateStaff = 'UPDATE_STAFF'
export const CreateStaff = 'Create_STAFF'
